// Autogenerated from Pigeon (v0.1.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTResponse;
@class FLTRequest;

@interface FLTResponse : NSObject
@property(nonatomic, copy, nullable) NSString * responseMessage;
@end

@interface FLTRequest : NSObject
@property(nonatomic, copy, nullable) NSString * unit;
@end

@protocol FLTApi
-(nullable FLTResponse *)add:(FLTRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi> _Nullable api);

NS_ASSUME_NONNULL_END
