// Autogenerated from Pigeon (v0.1.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = [NSDictionary dictionaryWithObjectsAndKeys:
        (error.code ? error.code : [NSNull null]), @"code",
        (error.message ? error.message : [NSNull null]), @"message",
        (error.details ? error.details : [NSNull null]), @"details",
        nil];
  }
  return [NSDictionary dictionaryWithObjectsAndKeys:
      (result ? result : [NSNull null]), @"result",
      errorDict, @"error",
      nil];
}

@interface FlutterWifiResponse ()
+(FlutterWifiResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FlutterBatteryResponse ()
+(FlutterBatteryResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FlutterBatteryRequest ()
+(FlutterBatteryRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation FlutterWifiResponse
+(FlutterWifiResponse*)fromMap:(NSDictionary*)dict {
  FlutterWifiResponse* result = [[FlutterWifiResponse alloc] init];
  result.availableWifi = dict[@"availableWifi"];
  if ((NSNull *)result.availableWifi == [NSNull null]) {
    result.availableWifi = nil;
  }
  result.availableMobile = dict[@"availableMobile"];
  if ((NSNull *)result.availableMobile == [NSNull null]) {
    result.availableMobile = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.availableWifi ? self.availableWifi : [NSNull null]), @"availableWifi", (self.availableMobile ? self.availableMobile : [NSNull null]), @"availableMobile", nil];
}
@end

@implementation FlutterBatteryResponse
+(FlutterBatteryResponse*)fromMap:(NSDictionary*)dict {
  FlutterBatteryResponse* result = [[FlutterBatteryResponse alloc] init];
  result.responseMessage = dict[@"responseMessage"];
  if ((NSNull *)result.responseMessage == [NSNull null]) {
    result.responseMessage = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.responseMessage ? self.responseMessage : [NSNull null]), @"responseMessage", nil];
}
@end

@implementation FlutterBatteryRequest
+(FlutterBatteryRequest*)fromMap:(NSDictionary*)dict {
  FlutterBatteryRequest* result = [[FlutterBatteryRequest alloc] init];
  result.unit = dict[@"unit"];
  if ((NSNull *)result.unit == [NSNull null]) {
    result.unit = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.unit ? self.unit : [NSNull null]), @"unit", nil];
}
@end

@interface FlutterWifiCallbackApi ()
@property (nonatomic, strong) NSObject<FlutterBinaryMessenger>* binaryMessenger;
@end

@implementation FlutterWifiCallbackApi
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger>*)binaryMessenger {
  self = [super init];
  if (self) {
    self.binaryMessenger = binaryMessenger;
  }
  return self;
}

- (void)apply:(FlutterWifiResponse*)input completion:(void(^)(NSError* _Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.WifiCallbackApi.apply"
      binaryMessenger:self.binaryMessenger];
  NSDictionary* inputMap = [input toMap];
  [channel sendMessage:inputMap reply:^(id reply) {
    completion(nil);
  }];
}
@end
void FlutterBatteryApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FlutterBatteryApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.BatteryApi.call"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FlutterBatteryRequest *input = [FlutterBatteryRequest fromMap:message];
        FlutterBatteryResponse *output = [api call:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
void FlutterWifiApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FlutterWifiApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.WifiApi.call"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FlutterWifiResponse *output = [api call:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
