// Autogenerated from Pigeon (v0.1.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FlutterWifiResponse;
@class FlutterWifiRequest;

@interface FlutterWifiResponse : NSObject
@property(nonatomic, strong, nullable) NSNumber * availableDetect;
@property(nonatomic, strong, nullable) NSNumber * availableWifi;
@property(nonatomic, strong, nullable) NSNumber * availableMobile;
@end

@interface FlutterWifiRequest : NSObject
@property(nonatomic, strong, nullable) NSNumber * isDetect;
@end

@interface FlutterCallbackApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)apply:(FlutterWifiResponse*)input completion:(void(^)(NSError* _Nullable))completion;
@end
@protocol FlutterApi
-(nullable FlutterWifiResponse *)call:(FlutterWifiRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FlutterApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FlutterApi> _Nullable api);

NS_ASSUME_NONNULL_END
