// Autogenerated from Pigeon (v0.1.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = [NSDictionary dictionaryWithObjectsAndKeys:
        (error.code ? error.code : [NSNull null]), @"code",
        (error.message ? error.message : [NSNull null]), @"message",
        (error.details ? error.details : [NSNull null]), @"details",
        nil];
  }
  return [NSDictionary dictionaryWithObjectsAndKeys:
      (result ? result : [NSNull null]), @"result",
      errorDict, @"error",
      nil];
}

@interface FLTResponse ()
+(FLTResponse*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTRequest ()
+(FLTRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation FLTResponse
+(FLTResponse*)fromMap:(NSDictionary*)dict {
  FLTResponse* result = [[FLTResponse alloc] init];
  result.responseMessage = dict[@"responseMessage"];
  if ((NSNull *)result.responseMessage == [NSNull null]) {
    result.responseMessage = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.responseMessage ? self.responseMessage : [NSNull null]), @"responseMessage", nil];
}
@end

@implementation FLTRequest
+(FLTRequest*)fromMap:(NSDictionary*)dict {
  FLTRequest* result = [[FLTRequest alloc] init];
  result.unit = dict[@"unit"];
  if ((NSNull *)result.unit == [NSNull null]) {
    result.unit = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.unit ? self.unit : [NSNull null]), @"unit", nil];
}
@end

void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.add"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FLTRequest *input = [FLTRequest fromMap:message];
        FLTResponse *output = [api add:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
