// Autogenerated from Pigeon (v0.1.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package nagano.shunsuke.plugins;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.ArrayList;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings("unused")
public class Pigeon {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class WifiResponse {
    private Boolean availableWifi;
    public Boolean getAvailableWifi() { return availableWifi; }
    public void setAvailableWifi(Boolean setterArg) { this.availableWifi = setterArg; }

    private Boolean availableMobile;
    public Boolean getAvailableMobile() { return availableMobile; }
    public void setAvailableMobile(Boolean setterArg) { this.availableMobile = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("availableWifi", availableWifi);
      toMapResult.put("availableMobile", availableMobile);
      return toMapResult;
    }
    static WifiResponse fromMap(HashMap map) {
      WifiResponse fromMapResult = new WifiResponse();
      Object availableWifi = map.get("availableWifi");
      fromMapResult.availableWifi = (Boolean)availableWifi;
      Object availableMobile = map.get("availableMobile");
      fromMapResult.availableMobile = (Boolean)availableMobile;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class BatteryResponse {
    private String responseMessage;
    public String getResponseMessage() { return responseMessage; }
    public void setResponseMessage(String setterArg) { this.responseMessage = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("responseMessage", responseMessage);
      return toMapResult;
    }
    static BatteryResponse fromMap(HashMap map) {
      BatteryResponse fromMapResult = new BatteryResponse();
      Object responseMessage = map.get("responseMessage");
      fromMapResult.responseMessage = (String)responseMessage;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class BatteryRequest {
    private String unit;
    public String getUnit() { return unit; }
    public void setUnit(String setterArg) { this.unit = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("unit", unit);
      return toMapResult;
    }
    static BatteryRequest fromMap(HashMap map) {
      BatteryRequest fromMapResult = new BatteryRequest();
      Object unit = map.get("unit");
      fromMapResult.unit = (String)unit;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents Flutter messages that can be called from Java.*/
  public static class WifiCallbackApi {
    private final BinaryMessenger binaryMessenger;
    public WifiCallbackApi(BinaryMessenger argBinaryMessenger){
      this.binaryMessenger = argBinaryMessenger;
    }
    public interface Reply<T> {
      void reply(T reply);
    }
    public void apply(WifiResponse argInput, Reply<Void> callback) {
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.WifiCallbackApi.apply", new StandardMessageCodec());
      HashMap inputMap = argInput.toMap();
      channel.send(inputMap, channelReply -> {
        callback.reply(null);
      });
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface BatteryApi {
    BatteryResponse call(BatteryRequest arg);

    /** Sets up an instance of `BatteryApi` to handle messages through the `binaryMessenger` */
    static void setup(BinaryMessenger binaryMessenger, BatteryApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.BatteryApi.call", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              BatteryRequest input = BatteryRequest.fromMap((HashMap)message);
              BatteryResponse output = api.call(input);
              wrapped.put("result", output.toMap());
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface WifiApi {
    WifiResponse call();

    /** Sets up an instance of `WifiApi` to handle messages through the `binaryMessenger` */
    static void setup(BinaryMessenger binaryMessenger, WifiApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.WifiApi.call", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              WifiResponse output = api.call();
              wrapped.put("result", output.toMap());
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static HashMap wrapError(Exception exception) {
    HashMap<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
