// Autogenerated from Pigeon (v0.1.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import
// @dart = 2.8
import 'dart:async';
import 'package:flutter/services.dart';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

class Response {
  String responseMessage;
  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final Map<dynamic, dynamic> pigeonMap = <dynamic, dynamic>{};
    pigeonMap['responseMessage'] = responseMessage;
    return pigeonMap;
  }
  // ignore: unused_element
  static Response _fromMap(Map<dynamic, dynamic> pigeonMap) {
    final Response result = Response();
    result.responseMessage = pigeonMap['responseMessage'];
    return result;
  }
}

class Request {
  String unit;
  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final Map<dynamic, dynamic> pigeonMap = <dynamic, dynamic>{};
    pigeonMap['unit'] = unit;
    return pigeonMap;
  }
  // ignore: unused_element
  static Request _fromMap(Map<dynamic, dynamic> pigeonMap) {
    final Request result = Request();
    result.unit = pigeonMap['unit'];
    return result;
  }
}

class Api {
  Future<Response> add(Request arg) async {
    final Map<dynamic, dynamic> requestMap = arg._toMap();
    const BasicMessageChannel<dynamic> channel =
        BasicMessageChannel<dynamic>('dev.flutter.pigeon.Api.add', StandardMessageCodec());
    
    final Map<dynamic, dynamic> replyMap = await channel.send(requestMap);
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null);
    } else if (replyMap['error'] != null) {
      final Map<dynamic, dynamic> error = replyMap['error'];
      throw PlatformException(
          code: error['code'],
          message: error['message'],
          details: error['details']);
    } else {
      return Response._fromMap(replyMap['result']);
    }
    
  }
}

